### ISSUE TITLE
where to enter the course link ?

### ISSUE THREAD

**Issue by Ledigh** [akinuri/linkedin-learning-downloader#2]
Hi!
where to enter the course link ?
Thanks

**Comment by akinuri** [comment]
Hi

When you run the `get-course-info.py` or the `get-course-links.py` file, it asks for it:

> Enter the course URL or slug:


If you're not familiar with Python, I'm afraid you need to fimiliarize yourself with Python first.

**Comment by Ledigh** [comment]
> Hi
> 
> When you run the `get-course-info.py` or the `get-course-links.py` file, it asks for it:
> 
> > Enter the course URL or slug:
> 
> If you're not familiar with Python, I'm afraid you need to fimiliarize yourself with Python first.

Thanks :)
